maplibre/maplibre-gl-js-docs

- .github/workflows/build-test-deploy.yml
- .github/workflows/build-test.yml
- docs/data/__tests__/__snapshots__/api-navigation.test.js.snap
This pull requests adds two GitHub Actions workflows:
* ```build-test``` which builds and tests the repo upon pull request to ```main```
* ```build-test-deploy``` which builds, tests, and deploys the documentation website to GitHub Pages on push to ```main```.
One test snapshot for ```api-navigation``` was not properly updated, which is fixed with commit 5dc725a.
To deploy to the gh-pages branch I use [this](https://github.com/JamesIves/github-pages-deploy-action) action from the marketplace which seems to work well.
> Continuous integration and deployment

- README.md
This pull requests updates the README.md file where it replaces ```Mapbox``` with ```MapLibre``` and ```mapbox``` with ```maplibre```.
> Replace Mapbox with MapLibre and mapbox with maplibre

- vendor/docs-page-shell/react-page-shell.js
This pull requests updates the link under the logo in the top left corner of the page to https://www.maplibre.org.
> Update logo link in top left corner to www.maplibre.org

- docs/components/example.js
This pull request removes the now unnecessary comment about the mapbox access token in the examples.
> Remove access token injection

- docs/pages/example/.eslintrc
This pull request updates the linter rules such that we can have for example ```var map = new maplibregl.Map()``` in the example files and pass all the tests.
> Allow maplibregl in examples by updating the linter configuration

- local.dic
This pull request adds ```MapLibre``` to the configuration file of @mapbox/copyeditor, which is a tool for spell checking the example markdown files.
> Add MapLibre to @mapbox/copyeditor config file

- docs/pages/example/simple-map.html
- docs/pages/example/simple-map.md
This pull request migrates the ```simple-map``` example, which serves as the hello world example on the front page, to MapLibre GL JS. We use maptiler (thanks to Petr Pridal @klokan) as a tile source for this with the api key specified in https://github.com/maplibre/maplibre-gl-js-docs/issues/2.
> Migrate example simple map

- docs/pages/example/3d-buildings.html
- docs/pages/example/3d-buildings.md
- docs/pages/example/3d-extrusion-floorplan.html
- docs/pages/example/3d-extrusion-floorplan.md
- docs/pages/example/add-a-marker.html
- docs/pages/example/add-a-marker.md
- docs/pages/example/add-image-animated.html
This pull request migrates 4 examples from mapbox to maplibre with maptiler streets as the vector data source.
I had to use full URLs in the markdown files as otherwise I would get the following linter error:
```
docs/pages/example/add-a-marker.md
18:15-18:67  error  Link to https://docs.mapbox.com/maplibre-gl-js-docs/api/markers/#marker is dead
link-checker-skip-external  remark-lint-mapbox
```
> Migrate example batch 1

- README.md
- docs/pages/api/index.md
This pull request adds a note about the migration from Mapbox to MapLibre to the readme and the front website.
I find that something like this is needed because there is some confusion about the status of the docs website, seen https://github.com/maplibre/maplibre-gl-js/discussions/69.
Feel free to change the wording.
> Add migration note to README.md and the frontpage

- .remarkrc.js
- docs/components/page-shell.js
- docs/components/style-spec/item.js
- docs/data/__tests__/__snapshots__/api-navigation.test.js.snap
- docs/data/api-navigation.js
- docs/data/style-spec-navigation.js
- docs/util/__tests__/__snapshots__/formatters.test.js.snap
- docs/util/__tests__/api-ref-redirect.test.js
- docs/util/__tests__/formatters.test.js
- docs/util/api-ref-redirect.js
- docs/util/linker.js
- docs/util/style-spec-redirect.js
- test/style-spec-redirect.test.js
- vendor/docs-page-shell/react-page-shell.js
This pull requests replaces ```docs.mapbox.com``` with ```maplibre.org``` and ```mapbox-gl-js``` with ```maplibre-gl-js-docs``` in all places that are relevant to automatic linking and side panel page navigation.
> Update urls and links

- docs/data/expressions-related.json
This pull request migrates the links that appear in the **Related** section of the style-spec [expressions page](https://maplibre.org/maplibre-gl-js-docs/style-spec/expressions/) from ```mapbox``` to ```maplibre```. 
Links to examples that have not been migrated are removed. Links to mapbox.com tutorials are removed as well.
Expressions that have no associated link are removed from ```expressions-related.json``` as otherwise the page would show the **Related** heading but no link below.
> Migrate links in style-spec/expressions to the maplibre examples

- README.md
- package.json
This pull request adds a link to the documentation website at the beginning of the readme and removes outdated information about manual deployment to GitHub pages - for this we have actions now.
> Clean-up deployment information

- docs/pages/api/index.md
* Thanks to @wipfli for the feedback and based on discussion from https://github.com/maplibre/maplibre-gl-js/pull/143.
* Adding a section called _Dependencies_ for use in the API Docs
> Add documentation on UNPKG for use in the API Docs.  

- batfish.config.js
- docs/components/__tests__/expression-metadata.test.js
- docs/components/expression-metadata.js
- docs/components/expressions.js
- docs/components/page-shell.js
- docs/data/style-spec-navigation.js
- docs/pages/style-spec/glyphs.md
- docs/pages/style-spec/layers.md
- docs/pages/style-spec/light.md
- docs/pages/style-spec/other.md
- docs/pages/style-spec/root.md
- docs/pages/style-spec/sources.md
- docs/pages/style-spec/sprite.md
- docs/pages/style-spec/transition.md
- docs/util/combine-items.js
- package-lock.json
- package.json
This pull request works towards replacing `@mapbox/mapbox-gl-style-spec` with `@maplibre/maplibre-gl-style-spec`. Currently this fails with
```
[19:05:57 Batfish] Error: Webpack compilation error.
./node_modules/@maplibre/maplibre-gl-style-spec/expression/types.js 3:7
Module parse failed: Unexpected token (3:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| // @flow
| 
> export type NullTypeT = { kind: 'null' };
| export type NumberTypeT = { kind: 'number' };
| export type StringTypeT = { kind: 'string' };
```
> Maplibre style spec

- docs/pages/example/3d-buildings.html
This addresses issue https://github.com/maplibre/maplibre-gl-js/issues/152
The source is changed from composite to openmaptiles, as can be seen when searching for the source in https://api.maptiler.com/maps/streets/style.json
This fixes the problem visible in the console at runtime for the 3d buildings example:
evented.js:140 Error: layers.3d-buildings: source "composite" not found
at Object.Bn [as emitValidationErrors] (validate_style.js:37)
at Ue (style.js:46)
at i._validate (style.js:1211)
at i.addLayer (style.js:677)
at r.addLayer (map.js:1888)
at r.<anonymous> ((index):4665)
at r.Ct.fire (evented.js:119)
at r._render (map.js:2511)
at map.js:2629
> Corrected the source in the 3d buildings example to match the style source

- docs/components/api/search.js
- docs/components/page-shell.js
Do we want to use a tracking tool? Do we use it at all?
I saw an error message in this [pull request](https://github.com/maplibre/maplibre-gl-js-docs/pull/59). With this PR, this error message disappears. 
But I honestly admit that I have not fully understood the tool yet.
This PR is intended more as a request for comments.
> [RFC] Remove tracking tool?

- .remarkrc.js
- package.json
Because of the `remark` configuration we can not use Maplibre as `product `name . I stumbled across this in https://github.com/maplibre/maplibre-gl-js-docs/pull/58. It is not possible to use `Maplibre GL JS` in https://github.com/maplibre/maplibre-gl-js-docs/pull/58/files#diff-604664e92c63ab379a8bdf863252857482ffd1f642e3cdd4223985ad9ca8a705 as `product `name. 
Thereby we would have the possibility to overwrite this via parameter.
Unfortunately, this ist not possible in our repositiory, if we use the package [remark-config-docs](https://www.npmjs.com/package/@mapbox/remark-config-docs) for creating the configuration.
Therefore, I removed the package [remark-config-docs] (https://www.npmjs.com/package/@mapbox/remark-config-docs) and added the same configuration statically.
A static …
> Do not use node package for creating remark config any more -> so we can exclude check for proudct,

- docs/data/__tests__/__snapshots__/api-navigation.test.js.snap
This pull request brings the docs website to the latest release of maplibre-gl-js: `v1.15.0`.
> Update submodule to maplibre-gl-js v1.15.0

- .github/workflows/update-gl-js.yml
This pull request adds a GitHub Action which 
* checks out the docs repos, 
* updates the submodule in `maplibre-gl-js` to the latest commit,
* creates a branch named with the new version (e.g. `v1.15.2`), 
* pushes the branch to `maplibre/maplibre-gl-js-docs`, 
* and creates a pull request to merge the new branch into `main`.
> Add workflow to automatically generate pull requests for the latest MapLibre GL JS version

- .github/workflows/update-gl-js.yml
Since a workflow cannot trigger another workflow (https://github.community/t/github-actions-workflow-not-triggering-with-tag-push/17053), we will get a pull request with the new version but the `build-test.yml` action does not run:
(https://github.com/maplibre/maplibre-gl-js-docs/pull/65)
Since I don't want to merge untested code I prefer running the tests before actually making a pull request. This is what this change does.
> Test before making a pull request

- docs/data/plugins.json
- docs/documentation.yml
When navigating the docs I ended up accidentally navigating the mapbox docs instead without realising, this was because I clicked a link to the style spec. Updated the links to direct to the map libre style spec pages instead as even though they are currently the same it keeps users within the correct documentation site.
> Link to map libre style spec consistently

- docs/data/plugins.json
I added my mapbox plugins on maplibre documentation. Could you merge them for me?
I have migrated `mapbox-gl-export` to maplibre, however other plugins are not yet shifted. I will update documentation again once I will migrate other plugins to maplibre.
- Changed plugin name from [mapbox-gl-export](https://github.com/watergis/mapbox-gl-export) to [maplibre-gl-export](https://github.com/watergis/maplibre-gl-export)
- added following mapbox plugins.
- [mapbox-gl-elevation](https://github.com/watergis/mapbox-gl-elevation)
- [mapbox-gl-valhalla](https://github.com/watergis/mapbox-gl-valhalla)
- [mapbox.photon](https://github.com/watergis/mapbox.photon)
> added some maplibre and mapbox plugins into docs

- docs/pages/example/3d-extrusion-floorplan.html
Thanks to maptiler who provide some data sources.
However, it's not mandatory for some demo.
Example here with: 3d-extrusion-floorplan
> Use token-free osm raster tiles

- docs/components/quickstart.js
- docs/pages/api/index.md
This pull request changes the title page of the docs website such that the example uses the MapLibre demotiles rather than the MapTiler tiles.﻿
> Use MapLibre demotiles on title page

- docs/data/__tests__/__snapshots__/api-navigation.test.js.snap
- package.json
~This is work in progress. Feel free to play around.~
This pull request adapts the documentation to MapLibre GL JS after the typescript migration. Only merge this once we publish `v2.0.0` on NPM.
> Update to MapLibre GL JS after Typescript migration

- docs/data/__tests__/__snapshots__/api-navigation.test.js.snap
- docs/documentation.yml
This pull requests bumps the GL JS submodule to v2.0.1, which includes hopefully the right format for the documentation of the addProtocol and removeProtocol functions.
It also removes include statements for accessToken and other Mapbox-related features that were removed in the TypeScript migrations.
﻿
> Bump GL JS submodule to v2.0.1 and include `addProtocol`

- docs/pages/example/add-image-stretchable.html
- docs/pages/example/animate-point-along-route.html
- docs/pages/example/filter-markers-by-input.html
- docs/pages/example/filter-markers.html
- docs/pages/example/popup-on-click.html
- docs/pages/example/popup-on-hover.html
> Use `text-overlap` and `icon-overlap`

- docs/data/plugins.json
TL;DR Using https://echarts.apache.org/en/index.html rather than broken https://ecomfe.github.io/echarts/index-en.html
https://ecomfe.github.io/echarts/index-en.html returns a 404 error
Clicking "ECharts - 数据可视化图表库" on https://ecomfe.github.io/ leads to https://echarts.baidu.com/ which says:
> ECharts 正在 Apache 开源基金会孵化中，因此域名已不再使用，请访问  echarts.apache.org
> ECharts is now under incubation at the Apache Software Foundation. So this domain name is no longer in
> use. Visit echarts.apache.org please
> Update plugins.json - Fix broken link to echarts

- docs/pages/example/add-3d-model.html
As seen in partly unrelated [issue](https://github.com/maplibre/maplibre-gl-js/issues/755), new users can be easily confused by the decision in the Add 3D Model example to render the example model below the road network layer.
To improve first impressions, this PR makes the 3D layer the topmost layer.
Before:
https://user-images.githubusercontent.com/1556222/159116367-1f007c6d-3190-43c4-be50-a2d93544fe7f.mp4
After:
https://user-images.githubusercontent.com/1556222/159116384-07aaafd3-3ebc-4a81-80b5-a0fa5b9aca35.mp4
It is good to note this is _not_ a fix for the actual mentioned occlusion issue in the original issue, but a remedy to the implementation of the example.
> Fix: In Add 3D Model example, make the 3D layer the topmost layer

- test/latest-version.test.js
It's not good that this repo's CI suddenly breaks out of nowhere because of the release cycle of another repo. Also, this will allow us to test that the docs can build pre-release versions of maplibre-gl-js
> Disable latest-version check to fix CI

- .github/workflows/build-test-deploy.yml
Updating the **JamesIves/github-pages-deploy-action** from @4.1.0 to @4.4.0 broke, because they presumably now want us to simply write @v4
> Fix github-pages-deploy-action

- .github/workflows/build-test-deploy.yml
- .github/workflows/build-test.yml
- .github/workflows/update-gl-js.yml
Until we update the submodule, node shouldn't automatically be set to 16.17 by our github actions, as it will break.
> Set node to 16.16, because 16.17 breaks

- docs/data/plugins.json
This PR  updates mapbox-gl-inspect to maplibre-gl-inspect
mapbox-gl-inspect does not work with maplibre. I have created a maplibre compatible fork at https://github.com/acalcutt/maplibre-gl-inspect
> use maplibre-gl-inspect in plugins list

- docs/pages/example/add-image-animated.html
The interface implemented in this example is [StyleImageInterface](https://maplibre.org/maplibre-gl-js-docs/api/properties/#styleimageinterface), not [CustomLayerInterface](https://maplibre.org/maplibre-gl-js-docs/api/properties/#customlayerinterface).
> Fix comment on animated image example

- docs/pages/style-spec/sources.md
This is in relation to https://github.com/maplibre/maplibre-gl-js/issues/2137
This adds Terrarium to the list of supported dem types. the text was copied from layers.md (hillshade)
> update dem info to include Terrarium

- docs/pages/api/index.md
- docs/pages/style-spec/layers.md
- docs/pages/style-spec/light.md
- docs/pages/style-spec/root.md
- docs/pages/style-spec/sources.md
- docs/pages/style-spec/transition.md
> Update dependencies docs

- docs/pages/example/3d-terrain.html
Adding a comment in the example code to indicate that users should use different sources for 3D terrain and hillshades. This seemed the most unintrusive way to add this note but happy to put it elsewhere if desired.
Regarding issue https://github.com/maplibre/maplibre-gl-js/issues/2035.
> comment in HTML example

- docs/pages/example/custom-style-layer.html
This example https://maplibre.org/maplibre-gl-js-docs/example/custom-style-layer/ can't open in jsfiddle/codepen because it needs a maptiler key. Use demotiles instead.
Also, the code is updated a bit from es5 to es6, and the shader which is the core of the example is updated from GLSL 1.0 (webgl1 shader)  to GLSL 3.0
> Fix custom style layer example

- docs/data/plugins.json
- docs/pages/example/contour-lines.md
Add https://github.com/onthegomap/maplibre-contour to the plugins page, and also fix punctuation on the examples page.
> Add maplibre-contour to plugins
