maplibre/maplibre-gl-js-docs

docs/pages/example/add-image-generated.html, docs/pages/example/add-image-missing-generated.html, docs/pages/example/add-image-stretchable.html, docs/pages/example/add-image.html, docs/pages/example/add-image.md, docs/pages/example/animate-a-line.html, docs/pages/example/animate-camera-around-point.html, docs/pages/example/animate-images.html, docs/pages/example/animate-images.md
This pull requests migrates another batch with 7 more examples from mapbox to maplibre. The vector tile source is maptiler streets.
=> Migrate example batch 2

docs/pages/example/animate-marker.html, docs/pages/example/animate-marker.md, docs/pages/example/animate-point-along-line.html, docs/pages/example/attribution-position.html, docs/pages/example/camera-animation.html, docs/pages/example/camera-animation.md, docs/pages/example/canvas-source.html, docs/pages/example/canvas-source.md, docs/pages/example/center-on-symbol.html, docs/pages/example/center-on-symbol.md
This pull request migrates 6 more examples.
=> Migrate example batch 3

docs/pages/example/change-case-of-labels.html, docs/pages/example/change-case-of-labels.md, docs/pages/example/check-for-support.html, docs/pages/example/check-for-support.md, docs/pages/example/cluster.html, docs/pages/example/cluster.md, docs/pages/example/color-switcher.html, docs/pages/example/color-switcher.md, docs/pages/example/custom-marker-icons.html, docs/pages/example/custom-marker-icons.md, docs/pages/example/custom-style-layer.html, docs/pages/example/data-driven-lines.html, docs/pages/example/data-driven-lines.md, docs/pages/example/disable-rotation.html, docs/pages/example/disable-scroll-zoom.html, docs/pages/example/drag-a-marker.html, docs/pages/example/drag-a-marker.md, docs/pages/example/drag-a-point.html, docs/pages/example/fill-pattern.html, docs/pages/example/fill-pattern.md
This pull request migrates 12 further examples from Mapbox to MapLibre.
=> Migrate example batch 4

docs/data/plugins.json
Added plug-ins for MapLibre GL JS
=> Added plug-ins for MapLibre GL JS

docs/pages/example/fitbounds.html, docs/pages/example/fitbounds.md, docs/pages/example/flyto-options.html, docs/pages/example/flyto-options.md, docs/pages/example/flyto.html, docs/pages/example/flyto.md, docs/pages/example/fullscreen.html, docs/pages/example/game-controls.html, docs/pages/example/geojson-layer-in-stack.html, docs/pages/example/geojson-layer-in-stack.md, docs/pages/example/geojson-line.html, docs/pages/example/geojson-line.md, docs/pages/example/geojson-markers.html, docs/pages/example/geojson-polygon.html, docs/pages/example/geojson-polygon.md
This pull request migrates 9 more examples.
=> Migrate example batch 5

docs/pages/example/animate-point-along-route.html, docs/pages/example/change-building-color-based-on-zoom-level.html, docs/pages/example/change-building-color-based-on-zoom-level.md, docs/pages/example/display-and-style-rich-text-labels.html, docs/pages/example/display-and-style-rich-text-labels.md, docs/pages/example/fallback-image.html, docs/pages/example/fallback-image.md, docs/pages/example/filter-markers-by-input.html, docs/pages/example/filter-markers-by-input.md, docs/pages/example/filter-markers.html, docs/pages/example/filter-markers.md, docs/pages/example/heatmap-layer.html, docs/pages/example/heatmap-layer.md, docs/pages/example/language-switch.html, docs/pages/example/language-switch.md, docs/pages/example/live-geojson.html, docs/pages/example/live-geojson.md, docs/pages/example/popup-on-click.html, docs/pages/example/popup-on-click.md, docs/pages/example/satellite-map.html, docs/pages/example/vector-source.html, docs/pages/example/vector-source.md, docs/pages/example/video-on-a-map.html
This pull request migrates 13 more examples. The map data sources are maptiler streets, basic, and hybrid.
=> Migrate example batch 8

docs/pages/example/add-3d-model.html, docs/pages/example/add-3d-model.md, docs/pages/example/cluster-html.html, docs/pages/example/cluster-html.md
This pull request migrates 2 more examples which I did not manage to migrate previously because I didn't understand the errors well enough yet.
=> Migrate example batch 9

docs/pages/example/third-party.html, docs/pages/example/timeline-animation.html, docs/pages/example/timeline-animation.md, docs/pages/example/toggle-interaction-handlers.html, docs/pages/example/variable-label-placement.html, docs/pages/example/variable-label-placement.md, docs/pages/example/visualize-population-density.html, docs/pages/example/visualize-population-density.md, docs/pages/example/wms.html, docs/pages/example/wms.md, docs/pages/example/zoomto-linestring.html, docs/pages/example/zoomto-linestring.md
This pull request migrates 7 more examples. MapTiler streets it used as the vector data source.
=> Migrate example batch 7

docs/pages/example/simple-map.html
=> Use demotiles for simple-map.html example

docs/pages/example/third-party.html
Changed endpoint, and changed layer name
=> Update Mapillary tile layer endpoint

docs/data/plugins.json
I've written a couple of little libraries compatible with both mapbox-gl and maplibre-gl which make it easier to consume Esri-based services.
=> Add Esri-service plugins

docs/pages/example/local-geojson.html, docs/pages/example/local-geojson.md
Add example for non-experimental reading of local geojson.
=> Add non-experimental local geojson example

docs/data/plugins.json
Hi ✋ 
I developed and released `maplibre-gl-temporal-control`, which make you enable to easily show animation from layers.
I wish this plugin can be on MapLibre GL JS docs, please check it 🙏
=> Add new plugin [maplibre-gl-temporal-control]

docs/components/api/related.js, package-lock.json, package.json
**This was barely tested; please try it out**
The change in related.js was probably made necessary by https://github.com/documentationjs/documentation/commit/48bb7a283e782b2398e7b4061b5edbcf3367bb87#diff-5cd6e4a33443db542ccef69418146704eed1596b7b14be9684d67471bb836451R234
=> Upgrade documentation to v13.2.5

README.md
=> Remove mapbox reference

.github/workflows/update-gl-js.yml
This should fix this error:
```
﻿Error message: Module not found: Error: Can't resolve '../../maplibre-gl-js/rollup/build/tsc/src/style-spec/reference/latest' in '/home/runner/work/maplib...
```
=> Run tsc in GL JS to build style spec

docs/data/plugins.json
adding these two plugins/tools I maintain to docs - cc @wipfli
=> add PMTiles plugin and sdf-glyph-tool

.github/dependabot.yml
=> Increase dependabot open pull request limit to 20

docs/pages/example/mapbox-gl-rtl-text.html
Demo: https://codesandbox.io/s/red-silence-ycbggl?file=/index.html
=> Switch to unpkg for mapbox-gl-rtl-text

package-lock.json, package.json
Main change is that v14 has support for import assertions, which we currently need.
=> Bump documentation from 13.2.5 to 14.0.0

package-lock.json, package.json
Update maplibre, so the docs cover the new camera options
=> Bump maplibre-gl from 2.3.0 to 2.4.0

docs/components/api/github.js
=> Fix broken github links

docs/data/plugins.json
Adding my new [maplibregl-mapbox-request-transformer](https://github.com/rowanwins/maplibregl-mapbox-request-transformer) plugin to the docs.
=> Add maplibregl-mapbox-request-transformer plugin

docs/data/plugins.json
Hi there! 
Just added  maplibre-gl-measures plugin to the list of plugins of the documentation. 
Hope everything is ok!
=> Added plugin maplibre-gl-measures

README.md, docs/bin/create-image.ts, docs/components/example.js, docs/data/__tests__/__snapshots__/api-navigation.test.js.snap, docs/data/api-navigation.js, docs/pages/api/index.md, docs/pages/api/properties.js, docs/pages/example/3d-buildings.md, docs/pages/example/animate-point-along-route.html, docs/pages/example/local-geojson.md, docs/pages/example/polygon-popup-on-click.html, docs/pages/example/popup-on-click.html, docs/pages/example/popup-on-hover.html, docs/pages/example/satellite-map.md, docs/pages/example/set-popup.html, docs/pages/style-spec/expressions.md, docs/pages/style-spec/glyphs.md, docs/pages/style-spec/index.md, docs/pages/style-spec/layers.md, docs/pages/style-spec/light.md, docs/pages/style-spec/other.md, docs/pages/style-spec/root.md, docs/pages/style-spec/sources.md, docs/pages/style-spec/sprite.md, docs/pages/style-spec/transition.md, docs/pages/style-spec/types.md
Changed some comments, fixed css stuff, removed some docs and code related to the access token, minor changes generally, I have not clue how to test this though...
Fixes #218
=> Remove some Mapbox related stuff

package.json
Fixes #384 
@krishnaglodha this should do the trick. Can you verify?
=> Add --openssl-legacy-provider to mitigate regression

docs/pages/api/index.md
The wording in the front of the docs is a bit dated. This update it and adds a reference to Native.
=> Update description of project in docs

docs/data/__tests__/__snapshots__/api-navigation.test.js.snap, package-lock.json, package.json
=> Update to maplibre 3.0.1

docs/data/__tests__/__snapshots__/api-navigation.test.js.snap, docs/documentation.yml
=> Add terrain control to docs
